### ISSUE TITLE
Inform TAM about JavaEE --> JakartaEE Namespace

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#111]
@StephanSST - would you / could you please take these information to the TAM group and inform them?

**Comment by MarkusTiede** [comment]
Thanks @luechtdiode for also stepping up: assigning accordingly.

**Comment by luechtdiode** [comment]
**Prepare for next TAM with @StephanSST:** 

Request to clarify the consequences of package-renaming `javax` -> `jakarta` in our codebase
eg. `javax.servlet.Servlet` -> `jakarta.servlet.Servlet`

**Comment by MarkusTiede** [comment]
IMHO done / addressed with evaluation of new application platform.

Closing for now: won't do. Please feel free to reopen at any time if necessary.
