### ISSUE TITLE
Describe / Automate Github Organization Onboarding

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#112]
https://github.com/baloise/open-source/blob/master/docs/md/guides/starting.md

**Comment by christiansiegel** [comment]
Reduce peribolos sync to only cover members and not groups/teams etc.
We can re-enable this during #283

**Comment by MarkusTiede** [comment]
I'd like to continue the work regarding the org(a) handling with individual issues such as https://github.com/baloise/org/issues/13 - hence closing this for now.
