### ISSUE TITLE
Process automatically reported security vulnerabilities in code repositories

### ISSUE THREAD

**Issue by RCBiczok** [baloise/open-source#116]

**Comment by RCBiczok** [comment]
![image](https://user-images.githubusercontent.com/538973/58479799-3acb8680-8159-11e9-9fc2-eaac0aa85429.png)

![image](https://user-images.githubusercontent.com/538973/58479819-47e87580-8159-11e9-8594-ee6464f9cdcd.png)

**Comment by MarkusTiede** [comment]
Closing for now: won't do. Please feel free to reopen at any time if necessary. For now we go with #178
