### ISSUE TITLE
Prepare: Red Hat Forum Switzerland 2019 - 45 min (15+15+15): Open Source enablement - How to establish a community

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#127]
# Insurance and Open-Source (Software) - (im)possible!?

When thinking about insurance companies **open-source** wouldn't be one of the first things that comes to your mind: unless when you think of [Baloise](https://baloise.github.io). For many years we've been "using", "contributing" and "releasing" open-source (software).

In this session Markus will give a brief overview of these activities and the road we've traveled so far. Markus will share (reusable) resources that will help you starting open-source activities on your own.

-----------------------

bio: https://github.com/MarkusTiede/about/blob/master/me.md#en
pic: https://github.com/MarkusTiede/about/blob/master/img/me-square.JPG

derived from #100

**Comment by MarkusTiede** [comment]
# Agenda

15 min - OS in general / our view
15 min - OS enablement by RedHat
15 min - Baloise Open Source

**Comment by MarkusTiede** [comment]
Placeholder presentation, with suggested title, content and structure. (by RedHat)

https://docs.google.com/presentation/d/1sQAsqyOQHpYtwMYfFYcGHSzgonVVYUyFU-JdKUcozUo/edit#slide=id.p

Agenda: http://red.ht/expandzurich

# Story line:
approx 30 mins:
Markus
- can you start your journey from the beginning- what was the reason to build up a own community 
Codrin
Role RH EOT team to act as a catalyst to help establish a community, encouraging it to be community (rather than Red Hat) led- can you deliver this part ?

approx 15 mins:
Markus
- Insurance and open source ? 15 Mins Best Practise Baloise 

Title Proposal:
Enable Open Source Culture -- Best Practise Open Source @Swiss Insurance Company

**Comment by codrinbucur** [comment]
Added slides for the "Red Hat and Open Source" and "Open Source Enablement by Red Hat Consulting" sections

**Comment by MarkusTiede** [comment]
First Version available: 
[RH Forum ZH 2019 - Open Source Enablement - How to Establish a Community.pdf](https://github.com/baloise/open-source/files/3584108/RH.Forum.ZH.2019.-.Open.Source.Enablement.-.How.to.Establish.a.Community.pdf)

**Comment by MarkusTiede** [comment]
Reviewd 2nd version: [RH Forum ZH 2019 - Open Source Enablement - How to Establish a Community.pdf](https://github.com/baloise/open-source/files/3591256/RH.Forum.ZH.2019.-.Open.Source.Enablement.-.How.to.Establish.a.Community.pdf)

**Comment by semioticrobotic** [comment]
@MarkusTiede and I spoke today about the possibility of turning this presentation into a future chapter in the [Open Organization books series](https://github.com/open-organization-ambassadors), which I would very much like to explore!

**Comment by MarkusTiede** [comment]
@semioticrobotic - I've filed #215 to track our ideas / progress.
