### ISSUE TITLE
Host event "PostgreSQL collations und Patroni mit Ansible" at Baloise

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#161]
Proposed date would be the : 20.02.2020

Evening event with PostgreSQL
 - technical input
 - projects (e.g. @mikevader about DB2 -> Postgres migration)
 - reference OS projects

**Comment by tbussmann** [comment]
I proposed to @danielwestermann to contribute a session on Collations in PostgreSQL on behalf of the SwissPUG.

**Comment by HeikoDammeyer** [comment]
We willl focus on two presenters:
@tbussmann 
@danielwestermann

I'll take care for the event coordination  togehter with daniel.

**Comment by danielwestermann** [comment]
@juliagugel would also be available to present her Patroni session

**Comment by MarkusTiede** [comment]
Thanks for the updates: however @HeikoDammeyer did you check with @mikevader whether we'll also contribute a talk to the event?

**Comment by MarkusTiede** [comment]
Ok (thanks @HeikoDammeyer  for the details) for now we'll stick with the [two presentations](http://mailman.swisspug.org/pipermail/announce/2019q4/000078.html):
- Collations in PostgreSQL by @tbussmann 
- Patroni & Ansible by [Julia Gugel](https://twitter.com/gugeljuli)
