### ISSUE TITLE
Evaluate / Setup Peribolos

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#169]
https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos

[![](https://img.youtube.com/vi/te3Xj2zr1Co/0.jpg)](https://www.youtube.com/watch?v=te3Xj2zr1Co)

**Comment by christiansiegel** [comment]
initial test with dedicated org -> looks good 👍 
https://github.com/christiansiegel-peribolos-test/org/blob/master/config.yaml

next step: automate peribolos sync via travis

**Comment by christiansiegel** [comment]
Travis automation works fine. We can even do a dry run for every PR:
https://github.com/christiansiegel-peribolos-test/org/blob/master/.travis.yml
