### ISSUE TITLE
Interview pour l'Argus de l'assurance

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#184]
https://www.argusdelassurance.com

@honeggera : Kannst du mir bitte bis am 11.2. einige Argumente / Antworten zu
- pour vous, qu’est-ce que l’Open Insurance ? Qu’en attendez-vous ?
- quel rôle jouent les API dans la révolution de l’Open Insurance ?
- API ouvertes / API fermées : pour quoi ? Pour qui ?
- Faire ou faire faire : la question se pose-t-elle de la même façon pour tous les projets ?

schicken?

**Comment by MarkusTiede** [comment]
Übersetzte Fragen
1. a) **Was ist für Sie Open-Insurance**? b) **Was erwarten Sie davon**?
1. **Welche Rolle spielen APIs in der Revolution / Entwicklung** von Open-Insurance?
1. **Offene / geschlossen APIs: a) Wofür? b) Für wen**?
1. **Machen oder machen lassen**: stellt sich diese Fragen in der gleichen Art für alle Projekte?

**Comment by NicoleTiede** [comment]
Übersetzte Fragen
1. a) **Was ist für Sie Open-Insurance**? b) **Was erwarten Sie davon**?
1. **Welche Rolle spielen APIs in der Revolution / Entwicklung** von Open-Insurance?
1. **Offene / geschlossen APIs: a) Wofür? b) Für wen**?
1. **Machen oder machen lassen**: stellt sich diese Fragen in der gleichen Art für alle Projekte?

**Comment by MarkusTiede** [comment]
# Frage 1
## a
## b

# Frage 2

# Frage 3
## a
## b

# Frage 4

**Comment by MarkusTiede** [comment]
PR - https://github.com/baloise/open-source/compare/markustiede/interview-pour-l-argus-184?expand=1
