### ISSUE TITLE
Evaluate usage of https://jitsi.org

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#200]
https://meet.jit.si/baloise/open-source-community

**Comment by MarkusTiede** [comment]
# Baloise infrastructure experience(s)
## ⚠️ OneClient: not recommended / does not work: use mobile device instead
### [click here for Apple iOS AppStore](https://itunes.apple.com/us/app/jitsi-meet/id1165103905)
### [click here for Google Play](https://itunes.apple.com/us/app/jitsi-meet/id1165103905)
## DWP works fine: no known issue(s)

**Comment by christiansiegel** [comment]
High client CPU usage also [reported by other users](https://community.jitsi.org/t/high-cpu-utilization-on-client-end/25764).
