### ISSUE TITLE
Cloud board approval for GitHub : Onboarding Setup Process - Guidelines annehmen pro MA

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#232]
Add PR template in
- https://github.com/baloise-incubator/org
- https://github.com/baloise/org

Each PR should link to the [Baloise Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/).

Each new member should state that he / she 
- [x] has read and understood our Open Source Guidelines
- [x] agrees to act accordingly 

before the organisation on-boarding is triggered.

**Comment by christiansiegel** [comment]
https://github.com/baloise/org/blob/master/docs/pull_request_template.md
https://github.com/baloise-incubator/org/blob/master/docs/pull_request_template.md
