### ISSUE TITLE
Baloise & GitHub with Dominik Bernert (nikbernert@github.com)

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#242]
via LinkedIn zum Thema: "Terms of Service"

**Comment by MarkusTiede** [comment]
kurze Vorstellungsrunde: @nikbernert, @culmat , @MarkusTiede 

aktuelle Themen
- https://github.community/t/download-from-github-package-registry-without-authentication/14407
- Kosten für Github Enterprise (damals) zu hoch; ggfs. interessant: Microsoft Subscription Benefits
- License Scanning? SPDX
- CodeSpaces <- -> gitpod

Terms of Service (for non Corporate contexts) -> Corporate ToS
- delete recovery
- no free plan available

wie schaffen wir - http://openfriday.org
- Einladung wahrnehmen? - 14.08
- cQL / static security code checks

**Comment by MarkusTiede** [comment]
Waiting for feedback from @nikbernert

**Comment by NikBernert** [comment]
Hi @MarkusTiede 👋 

Here's some more information based on our conversation yesterday:

- [GitHub Advanced Security](https://content.api.getguru.com/files/view/5a96d156-26a3-494d-aea6-cde63afdbaae) (SAST tool based on codeQL). Open source version can be tested [here](https://lgtm.com/). 
- re Terms of Service: The original purpose in creating a ToS specific to our corporate customers was to enable such customers to "own" the content in the accounts created on their behalf. (With the standard ToS, we presume ownership by the individual who went in and actually created the account.). With our corporate ToS we want to make it easier to identify the company as the owner of the account and grant access to the content, accordingly. I'm afraid there is no delta of the standard and corporate ToS, but if you are interested, you can take a look at the corporate ToS [here](https://docs.github.com/en/github/site-policy/github-corporate-terms-of-service). 
- Different [deployment methods](https://api.getguru.com/files/view/aa5e4704-f9f5-47c6-a026-b20360c0c9a4) of GitHub Enterprise (cloud and on-prem at the same time, if required).
- Requesting early access for [GitHub Codespaces](https://github.com/features/codespaces/)
- As you mentioned license management and Nexus, [here](https://github.com/features/security) is more information on our security features

As you seem entirely happy with your current setup, I suggest we keep in touch here. I am happy to provide you with more information on topics of your interest and could at a later stage involve my colleagues if you have pain points or are planning on changing your tool set. In the meantime, feel free to participate in our office hours where our experts showcase certain features and answer questions live. [Here](https://resources.github.com/webcasts/Code-scanning-office-hours-thankyou/) is the recording of our last office hours. The next office hours will take place on August 14. Hope this helps :)
