### ISSUE TITLE
Setup Peribolos for baloise-incubator

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#243]

**Comment by christiansiegel** [comment]
https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos
> Peribolos allows the org settings, teams and memberships to be declared in a yaml file. GitHub is then updated to match the declared configuration.

see also evaluation in #169

**Comment by christiansiegel** [comment]
https://github.com/baloise-incubator/org
See repo's open issues for current todos.

**Comment by MarkusTiede** [comment]
Next step: https://github.com/baloise-incubator/org/issues/8

**Comment by MarkusTiede** [comment]
- [ ]  Dry run timeout problematic ATM

**Comment by christiansiegel** [comment]
Peribolos dry-run issues fixed with latest version. See: baloise-incubator/org#11

**Comment by MarkusTiede** [comment]
@kullmanp  and I just asked ourselfs: whats the main purpose of performing a dry-run - @christiansiegel maybe you can elaborate on that?

**Comment by christiansiegel** [comment]
It just checks if the configuration is correct and could be applied. But as it seems to be quite unreliable I'd suggest to remove it.

**Comment by christiansiegel** [comment]
Removed dry-run on PRs (baloise-incubator/org#16)

**Comment by MarkusTiede** [comment]
@christiansiegel - the setup is imho done: we're now gathering feedback on the process. Would you agree closing this initial setup task?
