### ISSUE TITLE
Setup Peribolos for baloise main orga

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#244]

**Comment by culmat** [comment]
what is Peribolos?

**Comment by christiansiegel** [comment]
https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos
> Peribolos allows the org settings, teams and memberships to be declared in a yaml file. GitHub is then updated to match the declared configuration.

see also evaluation in #169

**Comment by christiansiegel** [comment]
https://github.com/baloise/org
