### ISSUE TITLE
Evaluate codeQL on e.g. on https://github.com/arburk/fishbone

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#245]
https://github.com/github/codeql

**Comment by culmat** [comment]
what is cQL ?

**Comment by arburk** [comment]
CodeQL
`QL is the query language that powers CodeQL. QL is an object-oriented logic programming language. GitHub, language experts, and security researchers create the queries used for code scanning, and the queries are open source. The community maintains and updates the queries to improve analysis and reduce false positives. For more information, see CodeQL on the GitHub Security Lab website.`
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code

**Comment by culmat** [comment]
see also 
https://semmle.com/codeql
https://lgtm.com/

**Comment by arburk** [comment]
conducted the tutorials https://help.semmle.com/QL/learn-ql/beginner/ql-tutorials.html and played around a little. Would like to discuss with someone also intereseted in this topic.

**Comment by MarkusTiede** [comment]
Let‘s do that!

**Comment by MarkusTiede** [comment]
## current status & ideas
- https://owasp.org/www-project-juice-shop/ (https://github.com/bkimminich/juice-shop/actions) is already using cQL
- https://github.com/arburk/fishbone trying to reproduce very simple cQL issues

## next steps
- 
- 
-

**Comment by MarkusTiede** [comment]
Next step(s)
- [ ] execute / run checks locally on dev-machines
- [ ] publish results within GitHub scope

Postponed
- [ ] execute / run checks on Jenkins CI

**Comment by arburk** [comment]
The generated **sarif** can be added as artifact by the following workflow step
```YAML
- name: Archive sarif files
    uses: actions/upload-artifact@v2
    with:
      name: Sarif file from codeQL scan
      path: /home/runner/work/fishbone/results/java-builtin.sarif
```
The path needs to be adjusted to related repo of course 😉

**Comment by MarkusTiede** [comment]
# agenda for security show & tell

**Comment by arburk** [comment]
Evaluation is completed so far. Followup story to be created for an integrated usage with Jenkins/Sonarqube
