### ISSUE TITLE
Migrate away from GitPitch (to reveal.js)?

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#260]
![image](https://user-images.githubusercontent.com/1764012/92602306-44292580-f2ae-11ea-859c-ab282b1fc97e.png)

**Comment by MarkusTiede** [comment]
https://github.com/gitpitch/gitpitch/issues/310

**Comment by leubedane** [comment]
Hi @MarkusTiede , if we upgrade all old pitches were broken (all that uses snap feature). So I would like to suggest to open a new repository for 4.0 gitpitches and try to migrate in in two steps.

What do you think about it?

**Comment by MarkusTiede** [comment]
I'd like to take this to the next bi-weekly: AFAICS 4.0 requires (if we continue to use it as today) a commercial subscription.

However how we migrate I'd first like to discuss (e.g. forking) also other possibilities. 

@leubedane: Will you make it to the next bi-weekly?

**Comment by MarkusTiede** [comment]
[![Bildschirmfoto 2020-12-03 um 10 30 17](https://user-images.githubusercontent.com/1764012/100990793-92b72a80-3552-11eb-9d72-0640be594f24.png)](https://twitter.com/gitpitch/status/1333504658023845891)

**Comment by janbrohl** [comment]
[S5 slideshows](https://en.wikipedia.org/wiki/S5_(file_format)) could be an alternative. They can also be [generated from rst markup](https://docutils.sourceforge.io/docs/user/slide-shows.html) by docutils.

**Comment by MarkusTiede** [comment]
Thanks for the input : my current preference is using "raw" reveal.js - which has otherwise been generated by gitpitch in the background.

**Comment by MarkusTiede** [comment]
- Asciidoc -> Reveal.js
- use fork from gitpitch 3 / contribute to community

**Comment by MarkusTiede** [comment]
Recommendation : switch to reveal.js instead with external markdown integration.
