### ISSUE TITLE
Evaluate container based (UI) test-automation solution(s)

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#272]
# aerokube / selenoid

https://aerokube.com/selenoid/latest/#_selenoid_in_kubernetes

## >> https://aerokube.com/moon/latest/#_installing_to_openshift

4 parallel pods for free ->> https://aerokube.com/moon/latest/#_pricing

**Comment by MarkusTiede** [comment]
We could do first (free) steps with moon on open shift within our incubator organization and the baloise.dev-OKD4 Cluster

https://github.com/baloise-incubator/okd4-cluster-infra-apps#okd4-cluster-infra-apps

**Comment by niiku** [comment]
I've setup moon, but didn't run any tests with it: https://moon.apps.baloise.dev/
https://github.com/baloise-incubator/okd4-cluster-infra-apps/tree/master/moon

**Comment by MarkusTiede** [comment]
Invoking a new browser session from outside e.g. via cURL seems to work pretty straight forward

```
curl -X POST 'https://moon.apps.baloise.dev:443/wd/hub/session' -d '{ 
            "desiredCapabilities":{
                "browserName":"MicrosoftEdge",
                "browserVersion": "88.0",
                "platformName":"ANY",
                "selenoid:options": {
                    "enableVNC": true, 
                    "enableVideo": false,
                    "sessionTimeout": "120s"
                }
            }
        }'
```

**Comment by niiku** [comment]
Moon could be called from Baloise client devices.
Don't forget to specify proxy arguments for the JVM:
```
-Dhttp.proxyHost=localhost -Dhttp.proxyPort=8888 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8888
```
And use the following URL which is running under port 80/http as the WebProxy certificate isn't imported in the truststore of the JVMs used:
```
http://moon-backend.apps.okd.baloise.dev
```
FYI: You cannot open http on .dev domains in newer browser (HSTS), but java/curl doesn't care.
