### ISSUE TITLE
sum.cumo - Open-Insurance: sum. cumo Insurance Platform SCIP

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#273]
https://www.asscompact.de/nachrichten/die-bayerische-verkauft-insurtech-sumcumo

https://versicherungswirtschaft-heute.de/unternehmen-und-management/2020-11-16/kooperation-statt-neid-so-veraendert-open-source-die-versicherungswirtschaft/

**Comment by honeggera** [comment]
Wo liegt der Quellcode von sum.cumo? Wie einfach ist er installierbar? welche Qualität hat er?

Welche Geschäftsfähigkeiten werden abgebildet?

**Comment by MarkusTiede** [comment]
# [sum.cumo GmbH](https://github.com/sumcumo)

https://www.sumcumo.com/en/insurers-need-to-rethink-technology

**Comment by MarkusTiede** [comment]
Add sum.cumo to our https://open-insurance.org/index/#s
