### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com until 2020-12-31

### ISSUE THREAD

**Issue by christiansiegel** [baloise/open-source#274]
travis-ci.org will be closed down December 31st, 2020:
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by christiansiegel** [comment]
affected repos:
- gitopscli (issue: baloise/gitopscli#121)
- _many_ more...  (see dashboard in https://travis-ci.org/)

**Comment by christiansiegel** [comment]
TODO: at least create a issue in every repo to notify the maintainers

**Comment by christiansiegel** [comment]
Created issues for all active repositories that still use travis-ci.org:
baloise/codes-and-texts#42
baloise/corellia#119
baloise/dashboard-plus#29
baloise/digital-signature#56
baloise/eslint-config-typescript#7
baloise/eZooKeeper#9
baloise/java#35
baloise/jenkins-maven-plugin#3
baloise/rocket-chat-rest-client#63
baloise/this-or-that#183
baloise/ui-library#168

**Comment by MarkusTiede** [comment]
Ask for archiving of projects that did not migrate (yet).

**Comment by MarkusTiede** [comment]
IMHO for the rest of the referenced projects above we should / could pro-actively file a PR for the travsi / GH-actions migration.

**Comment by MarkusTiede** [comment]
Resolving this parent issue and adding the individual child ones.
