### ISSUE TITLE
Baloise as location Sponsor for DINAcon 2021

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#285]
Kurze Anfrage / Feedback / Meinungsbild gewünscht: wir sind zZ für die Konferenzdurchführung der DINAcon  - https://dinacon.ch/uber-uns/ https://youtu.be/9rjWdqaZDJQ -  für 2021 auf der Suche nach einem Locationsponsor. Die Welle7 in Bern kann uns dieses Jahr leider nicht mehr mit der Bereitstellung entgegenkommen.

# Eckdaten

 - Durchführung (zZ unter starkem Vorbehalt hybrid) geplant für Ende Oktober : 1 Tag
 - Teilnehmerzahl, falls die normale Teilnehmerzahl on-site kämen: ~200
 - Raumbedarf: 1 Plenumsraum + 5-7 Kleinräume (max. 30 Personen)
 - Catering (Kaffee, Mittag und Apero) muss nicht zwingend gesponsert werden

 # Aufgrund
 - unserer guten Lage zum SBB / Nähe auch zum DACH Raum
 - unserer Möglichkeiten im zukünftig neuen AZA im BPO
 - unser Bestrebungen in Richtung Nachhaltigkeit

 glaube ich das könnte eine (sehr) gute Win-Win Situation sein: die Veranstaltung wird seit Jahren in der Schweiz durchgeführt, hat thematisch wenig Konkurrenz und einen sehr guten Ruf.

# Frage
 - Was haltet ihr von der Idee
 - Mag sich jmd von euch beiden gemeinsam mit mir hier tangential zum Locationsponsoring engagieren?

Danke für eurer Feedback & Grüsse,

Markus

**Comment by culmat** [comment]
Das Ausbildungszentrum im Baloise Park öffnet wahrscheinlich im Mai 2021. 
Von der Teilnehmerzahl sind wir im Plenum beschränkt auf max. 170 (das wird also knapp für die geschätzten 200 an diesem Event).
"Klassenzimmer" hätte es ausreichend für die Gruppenarbeit. Catering wäre über SV in den Zimmern und zum Lunch im Personal Restaurant (oder Möglichkeit Steh-Lunch im Vorraum).

**Comment by MarkusTiede** [comment]
Aktuell sieht es so aus, als wenn es ein hybrides Event werden wird:

![telegram-cloud-photo-size-4-5839375856072504238-y](https://user-images.githubusercontent.com/1764012/108323059-82fcc900-71c6-11eb-8fcc-8446f53de30c.jpg)

Ich nehme mal einfach an, dass 170 respektive bspw. 85 bei entsprechend notwendiger Reduktion ausreichend sein werden.

**Comment by MarkusTiede** [comment]
Some information regarding the location - Baloise Park Ost can be found here:

https://www.baloisepark.ch/de/baloise-park/zahlen-fakten.html

**Comment by MarkusTiede** [comment]
Aktuelle Fragen
- wie sicher ist die Öffnung im Mai?
- 170 auf in Corona Zeiten - oder was ist die maximale Anzahl im hybrid-Modus?
- Roomsponsoring kann als gegeben angesehen werden
- Cateringsponsoring: SV - oder sind auch Alternativen möglich 

Nächste Schritte
- Markus klärt offene obige Fragen
- Markus bucht für den 22.10 (alternativ 29.10) alle notwendigen Räume (Nachmittag vorher + den ganzen Tag)

**Comment by MarkusTiede** [comment]
Support DINAcon 2021 - Package : [Support DINAcon 2021.pdf](https://github.com/baloise/open-source/files/6004484/Support.DINAcon.2021.pdf)

**Comment by MarkusTiede** [comment]
# 29.10 ist noch alles frei -> primär (22.10)
- ist noch offen im 2. Stock (Plenum) + 3 weitere Räume - 1. Stock (2 Kleinräume)
- Vorschlag: Anfang Mai die "Kleinräume sowie Plenum" besichtigen
- Pläne sind vorhanden bei Markus

7 Kleinräume + Plenum (2 Beamer) : 4+1 im 1. OG und 3 im 2. OG - gebucht

**Comment by MarkusTiede** [comment]
Aktuelle Fragen
- Workshop Raum im 2. OG falls wir nur 3-4 Räume brauchen
- Kann man die kleinen Räume vergrössern indem man die Zwischenwände rausnimmt?
-

**Comment by MarkusTiede** [comment]
# Welle7
https://www.youtube.com/watch?v=9rjWdqaZDJQ
https://www.youtube.com/watch?v=7x6bDOvfh6s

## virtuell: https://www.youtube.com/watch?v=Y-CbbyLeQsA

**Comment by MarkusTiede** [comment]
Baloise sponsort die Lokalität sicher am 29.10. Sponsoring vom Catering ist noch in der Abklärung (Chance >50%).
