### ISSUE TITLE
Exchange with Zurich Insurance on next OXD - 14-15

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#296]
Wie sichert man ab, dass keine sensiblen Daten oder „Intellectual Propety“ geleackt werden (Sign-Off?).
Welche Formalien / OSS Lizenzbedingungen muss man als Firma berücksichtigen, bevor man als Contributor frisch einsteigt. (Quellcode-Ownership, Verantwortung am Schaden usw.)
Wie behaltet man einen Überblick über sämtliche Beiträge?

**Comment by RCBiczok** [comment]
It was a pleasant conversation. Very intensive session with lots of reference material and information to work with. Thank you, @christiansiegel @MarkusTiede
