### ISSUE TITLE
Use case : collaboration with external partners & colleges on shared code / re-used snippets

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#299]
e.g. https://github.com/FRI-DAY <-> Baloise

**Comment by MarkusTiede** [comment]
https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows

https://github.com/baloise-incubator/org/pulls?q=is%3Apr+is%3Aclosed

**Comment by niels-oz** [comment]
meeting minutes: 
- motivation and goal for this to find one (or more) appropriate and lightweight collaboration patterns for joint projects. Can be cross SBU or with partners from associated companies (e.g. Friday) or even with Co-Star companies.
- how we solved this so far: private github repo + fork AND/OR sharing stuff via email
- disadvanteges: (1) works only for sequential project without the need of keeping stuff in sync in the long run, (2) creates a blurry intellectual property situation (3) hides the progress we make in improving in group wide collaboration on actual projects
- therefore we'll try a Baloise Incubator Repo as a central code repo for the next similar project
