### ISSUE TITLE
MS Teams Connector

### ISSUE THREAD

**Issue by arburk** [baloise/open-source#303]
JAVA SDK for sending channel notifications via webhook

**Comment by arburk** [comment]
created repo https://github.com/baloise-incubator/ms-teams-connector and added initial implementation

**Comment by arburk** [comment]
Next steps

- [ ]  ask for code review
- [ ] move to baloise (not incubator)
- [ ] create relase
- [ ] announce for usage

**Comment by MarkusTiede** [comment]
Requires #304
