### ISSUE TITLE
Extend subscription on Docker Hub

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#308]
![sub](https://user-images.githubusercontent.com/1764012/126986589-1027b20e-0a42-4eba-bbe5-290f84ee56ed.png)

**Comment by dweber019** [comment]
We need the ability to integrate from Github to DockerHub and therefore we need a token ;) We need this for open source development with Keycloak / RHSSO.

**Comment by baopso** [comment]
![message](https://user-images.githubusercontent.com/6236843/126987905-dffd32cb-2269-44f6-baa8-ddd61bc99321.png)

**Comment by baopso** [comment]
![yearlySub](https://user-images.githubusercontent.com/6236843/126989462-65158bc3-c067-4347-aafb-38c6bf49037a.png)

**Comment by baopso** [comment]
![done](https://user-images.githubusercontent.com/6236843/127113261-ac660274-95c9-42ca-88ed-1d671686f944.png)

**Comment by baopso** [comment]
AFAICT this is sufficient for now.

**Comment by MarkusTiede** [comment]
![www docker com_pricing](https://user-images.githubusercontent.com/1764012/127520635-b0796096-583e-4fd8-a9a7-b6f865591da1.png)
