### ISSUE TITLE
Github Confluence Mirror - migrate <or> disable?

### ISSUE THREAD

**Issue by baopso** [baloise/open-source#310]

**Comment by MarkusTiede** [comment]
All agreed on archiving this (for the moment)

**Comment by MarkusTiede** [comment]
![image](https://user-images.githubusercontent.com/1764012/167593675-7fba40c5-75dc-4578-a7af-ea0c536c8d80.png)

**Comment by MarkusTiede** [comment]
Webhooks for both organizations have been disabled

https://github.com/organizations/baloise/settings/hooks
https://github.com/organizations/baloise-incubator/settings/hooks

**Comment by culmat** [comment]
Re enabled the hook, but it seems to have a bug see #133 
If we disabled this we should also delete / archive the confluence space, otherwise the content goes stale and update the internal documentation.
