### ISSUE TITLE
Prepare guide for well-defined general setup parameters for open collaboration

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#32]
This includes, but is not restricted to issues like
- #1 
- #22 
- #25 

The guide should at least ease the steps [1-3](https://baloise.github.io/open-source/docs/md/goals/uplift.html).

**Comment by culmat** [comment]
Also provide guidance for documentation
- markdown on code branch
- github wiki
- github pages
  - jekyll
  - client side rendering, ie http://strapdownjs.com/ ( see http://culmat.github.io/jsTreeTable/ )
  - jbake ( see http://orig-in.github.io/ ) 
  - asciidoc ( see https://open-prevo.github.io/openprevo/ ) 
- https://readthedocs.org/
- https://gitpitch.com/
...

**Comment by MarkusTiede** [comment]
> Also provide guidance for documentation
> 
> * markdown on code branch
> * github wiki
> * github pages
>   
>   * jekyll
>   * client side rendering, ie http://strapdownjs.com/ ( see http://culmat.github.io/jsTreeTable/ )
>   * jbake ( see http://orig-in.github.io/ )
>   * asciidoc ( see https://open-prevo.github.io/openprevo/ )
> * https://readthedocs.org/
> * https://gitpitch.com/
>   ...

Good idea: however I'd like to keep the guidelines as agnostic to technology as possible. Hence: could you open another issue like "best practices and tools to implement our guidelines"?

**Comment by MarkusTiede** [comment]
Major points have been resolved with #58 - resolving accordingly.

**Comment by MarkusTiede** [comment]
[2018-10-12 Kick-Off Baloise Open Source Guidelines.pdf](https://github.com/baloise/open-source/files/3954601/2018-10-12.Kick-Off.Baloise.Open.Source.Guidelines.pdf)
