### ISSUE TITLE
FHNW - OSS und OGD in der Studienrichtung DBVN

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#331]
# prepare

1. Create account @Github & bring laptop: https://github.com/signup
2. watch : https://youtu.be/SpeDK1TPbew
3. prepare for 19.05
 - your (personal) **goals & aims, questions, problems, thoughts** as comments
   - one comment per person please here
   - https://github.com/baloise/open-source/issues/331#issuecomment-1122400146
   - 💡 please also feel free to "upvote" existing comments via 👍
 - optional: please bring your "No 🥇" open source project that you already came in touch with

# slides

## source: https://github.com/open-co-de/2022-fhnw-dbavn-oss

**Comment by FHNWPhilippeMaurer** [comment]
Ziele: Open-Source-Software und den Mehrwert für Nutzer und Unternehmen besser verstehen. Absichten: Welche Absichten verfolgen die Software-Anbieter? Gibt es Vorteile abseits der Nutzer und Unternehmen, da gewisse Software-Anbieter einen Marktwert von mehreren Milliarden haben? Fragen: Was ist der Unterschied zwischen der kostenlosen Nutzung und der kostenpflichtigen Nutzung von Open-Source-Software? Wieso ist Open-Source überhaupt kostenlos? Probiert man somit mehr potenzielle Kunden abzufangen? Probleme: Die Open-Source-Bewegung konzentriert sich lediglich auf technische und wirtschaftliche Fragestellungen. Gedanken: Die freie Software wird vernachlässigt durch die Konzentration auf technische und wirtschaftliche Fragestellungen.
Name: Philippe Maurer

**Comment by leahuber** [comment]
Ziele und Absichten: 
- Open Source legt den Quellcode kostenlose für Dritte offen. 
- Jeder und jede kann den Code einsehen und beliebig verändern. 
- Ein Ziel ist es Fehler schnell zu finden. Dank der grossen Community werden viele Reviews gemacht, welche die Fehler aufdecken. Die Software kann modifiziert und an eigene Bedürfnisse angepasst werden. 

Fragen: 
- Wie lässt sich mit Open Source Geld verdienen?
- Wem gehören die Codes rechtlich? 
- Kann ich irgendwelche Codes weiterverkaufen?

Probleme: 
- Open Source ist abhängig von einer aktiven Community.
- Weiter erhält man keinen Support und auch keine Garantie. 
- Zudem können Angreifer Schwachstellen in einem Projekt schnell ausfindig machen.
(Pros und Contra: https://t3n.de/news/open-source-software-pro-contra-1145742/)

Gedanken: Ich persönlich hätte Bedenken was den Datenschutz anbelangt. 

Name: Lea Huber

**Comment by jgrueter** [comment]
## Ziele und Absichten
* Mitarbeit ermöglichen
* Aufzeigen seiner Hobby-Projekte und Kompetenzen
* Zur Verfügung stellen von toller Software

## Fragen
* Wie kann die Nachhaltigkeit von OSS sichergestellt werden?

## Probleme
* Communityabhängigkeit
* Kommerzialisierung der Projekte
* Lizenzmissbrauch (unerlaubtes Kopieren in bspw. Closed Source-Projekte)

## Gedanken
* Open Source-Bewegung hat zuletzt gefühlt mehr Boden gewonnen
  * NSA-Überwachungsskandal, Social Credit-Systeme haben tlw zu mehr Misstrauen geführt

## No. 1 OSS-Projekt(e)
* [Linux](https://github.com/torvalds/linux) / [Android](https://source.android.com/)
* [Greenshot](https://github.com/greenshot)

**Comment by jasilicious** [comment]
Ziele/Absichten
Alle können den Quellcode einsehen und an die eigene Unternehmung anpassen. Dies verringert die Abhängigkeit zu einem bestimmten Anbieter.

**Fragen**
Wieso stellt man den Quellcode gratis zur Verfügung? Andere könnten meinen Code nehmen und ihn weiterverkaufen.
Wem gehört der Code, wenn er von mehreren Personen erstellt worden ist?

**Probleme**
Lizenzmissbrauch, kein Support

**Gedanken**
Ich finde es wichtig, dass sich Personen/Unternehmen für eine offene und kollaborative Software einsetzen. Die kostenlose Nutzung dieser Codes eröffnet Chancen, welche sonst allenfalls nicht möglich wären.

Name: Jasmin Gremlich

**Comment by alessia911** [comment]
**Absichten**
Als Open Source wird Software bezeichnet, deren Quelltext öffentlich und von Dritten eingesehen, geändert und genutzt werden kann. Open-Source-Software kann meistens kostenlos genutzt werden.

**Fragen**
Weshalb is Open Source kostenlos?
Wieso kann es verändert werden? Profitiert der ursprüngliche Ersteller auch von der geänderten Software?

**Probleme**
Keine rechtliche Grundlage
Keine Anbieterunterstützung
Keine oder fast keine Dokumentation

**Gedanken** 
Ich verstehe noch nicht ganz, weshalb eine Software kostenlos zur Verfügung gestellt wird, die abgeändert werden kann und so vielleicht den Ursprungsnutzen komplett verfehlt.

Name: Alessia Gru

**Comment by KevinFH98** [comment]
**Ziele**

- Open Source zu verstehen und den Nutzen davon zu verstehen.

**Fragen**

- Wie kann durch Open Source Geld verdient werden?
- Kann es durch Open Source nicht schnell zu kopieren bzw. zu stehlen von Ideen kommen?

**Probleme**

- Die komplexen Lizenzbedingungen
- Verträge müssen sorgfältig gestaltet werden

**Gedanken**

- Meiner Meinung ist es ein sehr spannender Ansatz und ich habe noch keinerlei Erfahrung mit Open Source.
- Deshalb freue ich mich die Grundlagen kennenzulernen und mich damit zu beschäftigen!

Name: Kevin Gerber

**Comment by jonathanlerch** [comment]
**Absichten**
OSS nutzt die Netzwerkeffekte und die Skalierung der Community in der Softwareentwicklung. Jede OSS ist somit nicht das Resultat von "wenigen" Personen, welche viel beigetragen haben, sondern eine Errungenschaft von vielen Personen, welche im Gesamtkontext eher wenig beigetragen haben, was zu einer stetigen Verbesserung der Software führt. Der Quellcode der Basissoftware ist öffentlich und kann von Dritten eingesehen, geändert und genutzt werden . Die Basissoftware von OSS ist dabei kostenlos verfügbar, Geld wird über Zusatzdienste und Support generiert.

**Fragen**
Was sind die Vorteile von geschlossenen Systemen ggü OSS?

**Probleme**
- Datenschutz?
- Cyber Security?
- Klare Produktausrichtung: Viele Personen arbeiten am selben Produkt, haben aber ganz andere Intensionen und Ziele.

**Gedanken**
OSS Prinzip kann auch als "Lockvogel" dienen, damit sich die Leute für eine Anwendung registrieren, für die effektiv hilfreichen Dienste anschliessend aber Geld bezahlen müssen. Die Quellcodes der Zusatzdienste sind dann womöglich nicht mehr offen.

**No 1 OSS**
- R and RStudio
- GitHub

Jonathan Lerch

**Comment by FHNWdelaja** [comment]
**Absichten**
Open Source Software stellt Quelltext öffentlich zur verfügung / kann frei kopiert und geändert werden / keine Vorschriften in der Verwendung

**Fragen**
Wieso sollte man sich als Software-Entwickler für eine Open Source Software entscheiden? 
Wie steht es um Gefahren in der Nutzung? Gibt es Fälle von versteckten Cyber Security Vorfällen? 

**Probleme**
Ändert sich immer wieder - keine Dokumentation / Nachverfolgung anspruchsvoll 
Datenschutz / Datensicherheit
Rechtliche Grundlage nicht vorhanden

**Gedanken**
Persönlich finde ich Open Source Softwares interessant, ich weiss allerdings nicht ob ich es in einem geschäftlichen Umfeld ausgeprägt nutzen würde, da ich mir sorgen um die Datensicherheit machen würde. 

Name: Delaja L.

**Comment by FeliE1** [comment]
**Ziele/Absichten**
Open-Source-Software stellt eine Software dar, bei welcher der Quellcode öffentlich zugänglich ist. Dier kann beliebig kopiert und angepasst werden. Der Nutzen dabei ist, dass diverse Personen am Quellcode arbeiten und damit diverse Ideen eingebracht aber auch hinterfragt werden. Der Quellcode wird stetig verbessert.

**Fragen**
- Wie werden Missbrauch Fälle verhindert? 
- Wieso sollten sich Unternehmen auf die OSS verlassen?

**Gedanken**
Ich finde der Gedanken der OSS sehr interessant. Es können Kosteneinsparungen in der der Entwicklung generiert werden und es treffen viele verschiedene Ideen und Meinungen von Programmierern aufeinander. Der Ansatz, der gemeinsamen Erarbeitung eines Produktes/DL, könnte auf weitere Branchen erweitert werden, beispielsweise in der Medizin. Da hat sich in der Covid-Pandemie einmal mehr gezeigt, dass gemeinsam schneller Lösungen (Impfstoffe) entwickelt werden können.

Name: Eliana Felice

**Comment by djellzel** [comment]
**Frage**
Google Analytics vs. Matomo -> weshalb soll ein Unternehmen auf Matomo (Open Source) umsteigen?

**Comment by MarkusTiede** [comment]
Feedback: https://nuudel.digitalcourage.de/oX18Ruk1DOdsnhFF
