### ISSUE TITLE
Sponsoreship POSTGRESQL EUROPE

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#54]
Wir wurden angefragt, ob die Baloise als Sponsor der PostgreSQL Conference 2019/Leipzig auftreten moechte. Die Kosten dafür halten sich im Rahmen:

http://2018.pgconf.de/de/sponsoring.html

Waere das etwas für unsere OpenSource Initiative?

**Comment by MarkusTiede** [comment]
IMHO being a Bronze or Silver Sponsor sounds perfect: We've done this before e.g. #55

We often do it in combination: participate (as you often get free entry) and low-/medium level sponsoring.

E.g. with the #55 sponsoring the effective sponsoring price was 200 CHF whereas we get (larger) visibility in exchange.

**Comment by MarkusTiede** [comment]
@HeikoDammeyer do you plan to participate?

**Comment by HeikoDammeyer** [comment]
@MarkusTiede 
currently not planned, but I'll go to [https://2018.pgconf.eu](https://2018.pgconf.eu/)

**Comment by MarkusTiede** [comment]
Maybe it might be worth thinking about sponsoring [them](https://2018.pgconf.eu/becomesponsor/)? The delta is also ~300 CHF (€500 excl. VAT - 270€ for Standard Ticket)

**Comment by MarkusTiede** [comment]
As far as I understood there is currently no longer a necessity for this issue - resolving accordingly.
