### ISSUE TITLE
Rename arc42 to Open Source Guidelines

### ISSUE THREAD

**Issue by culmat** [baloise/open-source#60]
https://github.com/baloise/open-source/tree/master/docs/arc42
-> 
https://github.com/baloise/open-source/tree/master/docs/OpenSourceGuidelines

**Comment by MarkusTiede** [comment]
I'd like to keep arc42 for now (many URLs point to this already) - If we're changing it I'd propose

https://github.com/baloise/open-source/tree/master/docs/guidelines
