### ISSUE TITLE
Release project "This or That"

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#74]

**Comment by jordilaforge** [comment]
Sorry but we have to wait till the pilot phase is over

**Comment by MarkusTiede** [comment]
@jordilaforge : sure - thanks for noticing! However I'd like to keep this as a placeholder (open) if that is ok with you!

**Comment by MarkusTiede** [comment]
https://github.com/baloise/this-or-that has been created; continuing there.
