### ISSUE TITLE
Open Source: AppStarter and ClientMessaging

### ISSUE THREAD

**Issue by luechtdiode** [baloise/open-source#94]
Abstract
=====
As mentioned in #18, we found a candidate to move in the public open source domain:
Actually, Appstarter and ClientMessaging is a tiny piece of infrastructure to integrate rich- and web-clients by adding the capability to launch other apps and to transfer context-information that initializes the started app to continue a app-overspanning usecase.
Appstarter is also for most usecases able to replace the JNLP Runtime of the legacy JRE-distributions.

There are some baloise-specific parts, that should be generalized. Also, there are some parts, that could be replaced by other open source libraries.

Here a short braindump to be discussed
==========================

Dependencies
----------------
- filsystem => make own opensource-lib
- clientmessaging => make own opensource-lib, integrate in starter to host clientmessaging-server
- resources => make own opensource-lib or eliminate and use standard i18n features
- swingframework => eliminate, write new UI

Design
---------

Goal: msi-installer with windows 10 64 compatible binaries
		- containing jre11, (ev. downsized with jigsaw)

Specification
---------------
- plugable jre-folder
- built with openjdk11 or later
- built on travis with openjdk-tooling
- pure-java (eliminate delphi-dependency with bvStarter.exe)
- integrate clientmessaging-server
- one binary to start applications (merge bvStarter.exe AppStarter.cmd and ClientMessagingServer).
- compose those as independent libraries (filsystem, clientmessaging).
- act as URL-Adapter with the "target:///"-schema, automatically registered by the msi-installer.
		
Configurable Items (ev. with installer-wizard)
-------------------------------------------------
- appStarter.properties
- Webstart baseUrl
- Environment-Qualifiers (defaults Test, Int, Acc, Prod)
- JRE's (ev. autoconfig from a common jre-folder)
- Startlink-List (ClientMessaging) or a new concept for that feature

**Comment by MarkusTiede** [comment]
Thanks for this detailed proposal @luechtdiode!

**Comment by luechtdiode** [comment]
Also interesting move at the moment: https://github.com/karakun/OpenWebStart

**Comment by MarkusTiede** [comment]
Closing for now - please feel free to re-open.
