### ISSUE TITLE
First exchange with IT-CH CCO and line CXOs - 02.04.2019

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#96]
Agenda
- welcome and expectations of participants
- [introduction slides](https://gitpitch.com/baloise/open-source/master?p=docs/slides/intro-short-intern)
- open discussion / ideas

Not discussed [Why Open Source](https://github.com/baloise/open-source/raw/master/docs/slides/Why_Open_Source.pptx)

**Comment by culmat** [comment]
Here are the flips with the expectations 

![2019_04_02 19_17_OS_expectations_1](https://user-images.githubusercontent.com/638519/56563151-456b8c80-65ab-11e9-88ae-f6c75c0d3c47.jpg)
![2019_04_02 19_17_OS_expectations_2](https://user-images.githubusercontent.com/638519/56563153-46042300-65ab-11e9-945d-ec6d1dc3801f.jpg)

**Comment by MarkusTiede** [comment]
Key statements from my point of view
- a general baseline for open-source @ Baloise has been set
- no major objections
- general agreement that applying OS principles is more than useful: maybe also pushing **inner source** in parallel would be more than useful (on group level as well as in individual SBUs)
- thinking / working in an OS manner from the beginning would be very useful - searching for projects that would fit

**Comment by MarkusTiede** [comment]
Agenda for today
- follow potential projects: commission system, IFRS
- Open Source Framework
  - what's necessary for [guideline](https://baloise.github.io/open-source/docs/arc42/) approval
  - [SECC - CM OS](https://github.com/orgs/baloise/teams/it-ch_secc_cm_open-source/members)
- what do you need from us?
- merge / extend exchange round with CXOs
- steps in Open-Insurance container 
- next workshop / exchange
  - explain inbound open source

**Comment by MarkusTiede** [comment]
As a follow up to #99 - @culmat - do you want to attach the document e.g. to this issue?

**Comment by MarkusTiede** [comment]
Zusammenfassung IT-CH Open-Source Austausch
**Einleitung, grundlegende Erwartungen und Terminologie im Bereich Open-Source**

Vorstellung eines leichtgewichtigen Open-Source [Maturitätsmodells](https://baloise.github.io/open-source/docs/arc42/#_overview) und Einordnung der Baloise Aktivitäten. Konsens: Ebene 1 und 2 haben einen sehr positiven Einfluss auf die IT-CH. Für Aktivitäten und Projekte auf Ebene 3 und 4 braucht es [explizite Entscheide](https://baloise.github.io/open-source/docs/arc42/#_get_sign_off) der IT-CH. Diese müssen bei der zukünftigen Planung von Projekten berücksichtigt werden. Aktuell werden passenden Kandidaten für ein solches strategisches Projektvorhaben im Bereich Open-Source gesucht.

**Comment by MarkusTiede** [comment]
Internal communication is about to follow - resolving accordingly.
