### ISSUE TITLE
Cleanup PPT (rewrite history) / large bin content and attach it to issue instead

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/open-source#99]
Please do it :-) and cleanup content of c2d346c9b424cb8437622266feb648fc9a003616

**Comment by luechtdiode** [comment]
The pptx-slides aren't attached to #96 yet.
If @culmat decides to publish it in #96, he would upload a publishable version him self.

**Comment by MarkusTiede** [comment]
Thanks - resolving accordingly.

**Comment by MarkusTiede** [comment]
Done (again) by using `bfg --delete-files Why_Open_Source.pptx open-source`

**Comment by MarkusTiede** [comment]
https://rtyley.github.io/bfg-repo-cleaner/
